export const SET_ITEMS = [
    // SET_ITEMS
        {title: '미스터에그 세트', brand: 'set_items', item_no: 1, src: process.env.PUBLIC_URL + '/assets/set_items/Egg_set_1.png', sub_src: process.env.PUBLIC_URL + '/assets/set_items/Egg_set_1.png', cir_img: process.env.PUBLIC_URL + '/assets/set_items/Egg_set_3.png',title_img:process.env.PUBLIC_URL + '/assets/set_items/Egg_set_2.png', price: 7400, desc: 'Mr. Egg Set', opt_color:'#f593b3'},
        {title: '아메리칸 햄 치즈 세트',brand: 'set_items', item_no: 2, src: process.env.PUBLIC_URL + '/assets/set_items/ham_set_1.png', sub_src: process.env.PUBLIC_URL + '/assets/set_items/ham_set_1.png', cir_img: process.env.PUBLIC_URL + '/assets/set_items/ham_set_3.png',title_img:process.env.PUBLIC_URL + '/assets/set_items/ham_set_2.png', price: 8400, desc: 'American Ham Cheese Set', opt_color:'#ffd8c5'}, 
        {title: '베이컨 더블 치즈 세트',brand: 'set_items', item_no: 3, src: process.env.PUBLIC_URL + '/assets/set_items/bacon_1.png', sub_src: process.env.PUBLIC_URL + '/assets/set_items/bacon_1.png', cir_img: process.env.PUBLIC_URL + '/assets/set_items/bacon_3.png',title_img:process.env.PUBLIC_URL + '/assets/set_items/bacon_2.png', price: 8500, desc: 'Bacon Double Cheese Set', opt_color:'#f7f6c7'}, 
        {title: '햄 앤 치즈 프렌치 토스트 세트',brand: 'set_items', item_no: 4, src: process.env.PUBLIC_URL + '/assets/set_items/franch_1.png', sub_src: process.env.PUBLIC_URL + '/assets/set_items/franch_1.png', cir_img: process.env.PUBLIC_URL + '/assets/set_items/franch_3.png',title_img:process.env.PUBLIC_URL + '/assets/set_items/franch_2.png', price: 8400, desc: 'Ham and Cheese French Toast Set', opt_color:'#ddf2bf'}, 
        {title: '갈릭 베이컨 치즈 세트',brand: 'set_items', item_no: 5, src: process.env.PUBLIC_URL + '/assets/set_items/gar_1.png', sub_src: process.env.PUBLIC_URL + '/assets/set_items/gar_1.png', cir_img: process.env.PUBLIC_URL + '/assets/set_items/gar_3.png',title_img:process.env.PUBLIC_URL + '/assets/set_items/gar_2.png', price: 8900, desc: 'Garlic Bacon Cheese Set', opt_color:'#c8e9f1'}, 
        {title: '데리야끼 바베큐 세트', brand: 'set_items', item_no: 6, src: process.env.PUBLIC_URL + '/assets/set_items/teri_1.png', sub_src: process.env.PUBLIC_URL + '/assets/set_items/teri_1.png', cir_img: process.env.PUBLIC_URL + '/assets/set_items/teri_3.png',title_img:process.env.PUBLIC_URL + '/assets/set_items/teri_2.png', price: 9400, desc: 'Teriyaki BBQ Set', opt_color:'#fdced6'},
        {title: '아보홀릭 세트',brand: 'set_items', item_no: 7, src: process.env.PUBLIC_URL + '/assets/set_items/avo_1.png', sub_src: process.env.PUBLIC_URL + '/assets/set_items/avo_1.png', cir_img: process.env.PUBLIC_URL + '/assets/set_items/avo_3.png',title_img:process.env.PUBLIC_URL + '/assets/set_items/avo_2.png', price: 8900, desc: 'Avo Holic Set', opt_color:'#c3eed9'}, 
        {title: '베이컨 딥 치즈 번 세트',brand: 'set_items', item_no: 8, src: process.env.PUBLIC_URL + '/assets/set_items/deep_1.png', sub_src: process.env.PUBLIC_URL + '/assets/set_items/deep_1.png', cir_img: process.env.PUBLIC_URL + '/assets/set_items/deep_3.png',title_img:process.env.PUBLIC_URL + '/assets/set_items/deep_2.png', price: 9100, desc: 'Bacon Deep Cheese Bun Set', opt_color:'#f7d1ea'}, 
        {title: '클럽샌드위치 세트',brand: 'set_items', item_no: 9, src: process.env.PUBLIC_URL + '/assets/set_items/club_1.png', sub_src: process.env.PUBLIC_URL + '/assets/set_items/club_1.png', cir_img: process.env.PUBLIC_URL + '/assets/set_items/club_3.png',title_img:process.env.PUBLIC_URL + '/assets/set_items/club_2.png', price: 8900, desc: 'Club Sandwich Set', opt_color:'#a3efe9'}, 
        {title: '치킨클럽샌드위치 세트',brand: 'set_items', item_no: 10, src: process.env.PUBLIC_URL + '/assets/set_items/chic_1.png', sub_src: process.env.PUBLIC_URL + '/assets/set_items/chic_1.png', cir_img: process.env.PUBLIC_URL + '/assets/set_items/chic_3.png',title_img:process.env.PUBLIC_URL + '/assets/set_items/chic_2.png', price: 9400, desc: 'Chicken Club Sandwich Set', opt_color:'#f4e6e7'},
        {title: '햄 앤 치즈 길거리 토스트 세트',brand: 'set_items', item_no: 11, src: process.env.PUBLIC_URL + '/assets/set_items/street_1.png', sub_src: process.env.PUBLIC_URL + '/assets/set_items/street_1.png', cir_img: process.env.PUBLIC_URL + '/assets/set_items/street_3.png',title_img:process.env.PUBLIC_URL + '/assets/set_items/street_2.png', price: 8400, desc: 'Ham and Cheese K-Street Toast Set', opt_color:'#f2d5b5'}, 
        {title: '치즈 불고기 길거리 토스트 세트', brand: 'set_items', item_no: 12, src: process.env.PUBLIC_URL + '/assets/set_items/bul_1.png', sub_src: process.env.PUBLIC_URL + '/assets/set_items/bul_1.png', cir_img: process.env.PUBLIC_URL + '/assets/set_items/bul_3.png',title_img:process.env.PUBLIC_URL + '/assets/set_items/bul_2.png', price: 9400, desc: 'Cheese Bulgogi K-Street Toast Set', opt_color:'#fce8bd'},
        {title: '아보 베이컨 길거리 토스트 세트',brand: 'set_items', item_no: 13, src: process.env.PUBLIC_URL + '/assets/set_items/avo_str_1.png', sub_src: process.env.PUBLIC_URL + '/assets/set_items/avo_str_1.png', cir_img: process.env.PUBLIC_URL + '/assets/set_items/avo_str_3.png',title_img:process.env.PUBLIC_URL + '/assets/set_items/avo_str_2.png', price: 9400, desc: 'Avo Bacon K-Street Toast Set', opt_color:'#b4e2cc'}, 
        {title: '샐러드 1인 세트',brand: 'set_items', item_no: 14, src: process.env.PUBLIC_URL + '/assets/set_items/sal_1.png', sub_src: process.env.PUBLIC_URL + '/assets/set_items/sal_1.png', cir_img: process.env.PUBLIC_URL + '/assets/set_items/sal_3.png',title_img:process.env.PUBLIC_URL + '/assets/set_items/sal_2.png', price: 10900, desc: 'SALAD SET', opt_color:'#e1e8d5'}, 
        {title: '샌드위치 & 해쉬 & 반했드랍 2인 세트',brand: 'set_items', item_no: 15, src: process.env.PUBLIC_URL + '/assets/set_items/two_san_1.png', sub_src: process.env.PUBLIC_URL + '/assets/set_items/two_san_1.png', cir_img: process.env.PUBLIC_URL + '/assets/set_items/two_san_3.png',title_img:process.env.PUBLIC_URL + '/assets/set_items/two_san_2.png', price: 19900, desc: 'Sandwich & Hash & Half Boiled egg Set for 2 people', opt_color:'#e1e8d5'}, 
        {title: '샌드위치 & 해쉬 & 반했드랍 & 샐러드 3인 세트',brand: 'set_items', item_no: 16, src: process.env.PUBLIC_URL + '/assets/set_items/three_san_1.png', sub_src: process.env.PUBLIC_URL + '/assets/set_items/three_san_1.png', cir_img: process.env.PUBLIC_URL + '/assets/set_items/three_san_3.png',title_img:process.env.PUBLIC_URL + '/assets/set_items/three_san_2.png', price: 35100, desc: 'Sandwich & Hash & Half Boiled egg & Salad', opt_color:'#e1e8d5'}, 
];    
export const SANDWICH = [
    // SANDWICH
    {title: '아메리칸 햄 치즈', brand: 'sandwich', item_no: 17, src: process.env.PUBLIC_URL + '/assets/SANDWICH/ame_ham_1.png', sub_src: process.env.PUBLIC_URL + '/assets/SANDWICH/ame_ham_1_1.png', cir_img: process.env.PUBLIC_URL + '/assets/SANDWICH/ame_ham_3.png',title_img:process.env.PUBLIC_URL + '/assets/SANDWICH/ame_ham_2.png', price: 4600, desc: 'American Ham Cheese', opt_color:'#ffd8c5'},
        {title: '햄 앤 치즈 길거리 토스트',brand: 'sandwich', item_no: 18, src: process.env.PUBLIC_URL + '/assets/SANDWICH/ham_1.png', sub_src: process.env.PUBLIC_URL + '/assets/SANDWICH/ham_1_1.png', cir_img: process.env.PUBLIC_URL + '/assets/SANDWICH/ham_3.png',title_img:process.env.PUBLIC_URL + '/assets/SANDWICH/ham_2.png', price: 4900, desc: 'Ham & Cheese K-Street Toast', opt_color:'#f2d5b5'}, 
        {title: '미스터 에그',brand: 'sandwich', item_no: 19, src: process.env.PUBLIC_URL + '/assets/SANDWICH/mr_1.png', sub_src: process.env.PUBLIC_URL + '/assets/SANDWICH/mr_1_1.png', cir_img: process.env.PUBLIC_URL + '/assets/SANDWICH/mr_3.png',title_img:process.env.PUBLIC_URL + '/assets/SANDWICH/mr_2.png', price: 3900, desc: 'Mr. Egg', opt_color:'#f593b3'}, 
        {title: '베이컨 더블 치즈',brand: 'sandwich', item_no: 20, src: process.env.PUBLIC_URL + '/assets/SANDWICH/ba_dou_1.png', sub_src: process.env.PUBLIC_URL + '/assets/SANDWICH/ba_dou_1_1.png', cir_img: process.env.PUBLIC_URL + '/assets/SANDWICH/ba_dou_3.png',title_img:process.env.PUBLIC_URL + '/assets/SANDWICH/ba_dou_2.png', price: 4200, desc: 'Bacon Double Cheese', opt_color:'#f7f6c7'}, 
        {title: '데리야끼 바베큐', brand: 'sandwich', item_no: 21, src: process.env.PUBLIC_URL + '/assets/SANDWICH/tery_1.png', sub_src: process.env.PUBLIC_URL + '/assets/SANDWICH/tery_1_1.png', cir_img: process.env.PUBLIC_URL + '/assets/SANDWICH/tery_3.png',title_img:process.env.PUBLIC_URL + '/assets/SANDWICH/tery_3.png', price: 5400, desc: 'Teriyaki BBQ', opt_color:'#fdced6'},
        {title: '갈릭 베이컨 치즈', brand: 'sandwich', item_no: 22, src: process.env.PUBLIC_URL + '/assets/SANDWICH/gal_1.png', sub_src: process.env.PUBLIC_URL + '/assets/SANDWICH/gal_1_1.png', cir_img: process.env.PUBLIC_URL + '/assets/SANDWICH/gal_3.png',title_img:process.env.PUBLIC_URL + '/assets/SANDWICH/gal_2.png', price: 5200, desc: 'Garlic Bacon Cheese', opt_color:'#c8e9f1'},
        {title: '햄 앤 치즈 프렌치토스트', brand: 'sandwich', item_no: 23, src: process.env.PUBLIC_URL + '/assets/SANDWICH/ham_fr_1.png', sub_src: process.env.PUBLIC_URL + '/assets/SANDWICH/ham_fr_1_1.png', cir_img: process.env.PUBLIC_URL + '/assets/SANDWICH/ham_fr_3.png',title_img:process.env.PUBLIC_URL + '/assets/SANDWICH/ham_fr_2.png', price: 4900, desc: 'Ham & Cheese French Toast', opt_color:'#ddf2bf'},
        {title: '아보홀릭', brand: 'sandwich', item_no: 24, src: process.env.PUBLIC_URL + '/assets/SANDWICH/avo_h_1.png', sub_src: process.env.PUBLIC_URL + '/assets/SANDWICH/avo_h_1_1.png', cir_img: process.env.PUBLIC_URL + '/assets/SANDWICH/avo_h_3.png',title_img:process.env.PUBLIC_URL + '/assets/SANDWICH/avo_h_2.png', price: 5400, desc: 'Avo Holic', opt_color:'#c3eed9'},
        {title: '베이컨 딥 치즈 번', brand: 'sandwich', item_no: 25, src: process.env.PUBLIC_URL + '/assets/SANDWICH/be_deep_1.png', sub_src: process.env.PUBLIC_URL + '/assets/SANDWICH/be_deep_1_1.png', cir_img: process.env.PUBLIC_URL + '/assets/SANDWICH/be_deep_3.png',title_img:process.env.PUBLIC_URL + '/assets/SANDWICH/be_deep_2.png', price: 5400, desc: 'Bacon Deep Cheese Bun', opt_color:'#f7d1ea'},
        {title: '치킨 클럽샌드위치', brand: 'sandwich', item_no: 26, src: process.env.PUBLIC_URL + '/assets/SANDWICH/ch_club_1.png', sub_src: process.env.PUBLIC_URL + '/assets/SANDWICH/ch_club_1_1.png', cir_img: process.env.PUBLIC_URL + '/assets/SANDWICH/ch_club_3.png',title_img:process.env.PUBLIC_URL + '/assets/SANDWICH/ch_club_2.png', price: 6900, desc: 'Chicken Club Sandwich', opt_color:'#f4e6e7'},
        {title: '치즈 불고기 길거리 토스트', brand: 'sandwich', item_no: 27, src: process.env.PUBLIC_URL + '/assets/SANDWICH/ch_bul_1.png', sub_src: process.env.PUBLIC_URL + '/assets/SANDWICH/ch_bul_1_1.png', cir_img: process.env.PUBLIC_URL + '/assets/SANDWICH/ch_bul_3.png',title_img:process.env.PUBLIC_URL + '/assets/SANDWICH/ch_bul_2.png', price: 5900, desc: 'Cheese Bulgogi K-Sreet Toast', opt_color:'#fce8bd'},
        {title: '아보 베이컨 길거리 토스트', brand: 'sandwich', item_no: 28, src: process.env.PUBLIC_URL + '/assets/SANDWICH/avo_str_1.png', sub_src: process.env.PUBLIC_URL + '/assets/SANDWICH/avo_str_1_1.png', cir_img: process.env.PUBLIC_URL + '/assets/SANDWICH/avo_str_3.png',title_img:process.env.PUBLIC_URL + '/assets/SANDWICH/avo_str_2.png', price: 5900, desc: 'Avo Bacon K-Street Toast', opt_color:'#b4e2cc'},
    ];    
    
    export const SIDE = [
        // SIDE
        {title: '해쉬브라운', brand: 'side', item_no: 29, src: process.env.PUBLIC_URL + '/assets/side/1702000810(0).png', sub_src: process.env.PUBLIC_URL + '/assets/side/1702000810(0).png', cir_img: process.env.PUBLIC_URL + '/assets/side/hash_3.png',title_img:process.env.PUBLIC_URL + '/assets/side/hash_2.png', price: 1800, desc: 'Hash Brown', opt_color:'#ffcdb4'},
        {title: '베이컨 체다 해쉬브라운',brand: 'side', item_no: 30, src: process.env.PUBLIC_URL + '/assets/side/1702000970(0)(1).png', sub_src: process.env.PUBLIC_URL + '/assets/side/1702000970(0)(1).png', cir_img: process.env.PUBLIC_URL + '/assets/side/b_hash_3.png',title_img:process.env.PUBLIC_URL + '/assets/side/b_hash_2.png', price: 2400, desc: 'Bacon Cheddar HashBrown', opt_color:'#f6d0d9'}, 
        {title: '콘치즈 해쉬브라운',brand: 'side', item_no: 31, src: process.env.PUBLIC_URL + '/assets/side/c_hash_1.png', sub_src: process.env.PUBLIC_URL + '/assets/side/c_hash_1.png', cir_img: process.env.PUBLIC_URL + '/assets/side/c_hash_3.png',title_img:process.env.PUBLIC_URL + '/assets/side/c_hash_2.png', price: 2400, desc: 'Corn Cheese Hash Brown', opt_color:'#fbe7b4'}, 
        {title: '리얼 에그 콥 샐러드',brand: 'side', item_no: 32, src: process.env.PUBLIC_URL + '/assets/side/egg_cob_1.png', sub_src: process.env.PUBLIC_URL + '/assets/side/1646442177(0).png', cir_img: process.env.PUBLIC_URL + '/assets/side/egg_cob_3.png',title_img:process.env.PUBLIC_URL + '/assets/side/egg_cob_2.png', price: 8200, desc: 'Real Egg Cobb Salad', opt_color:'#f0ffaa'}, 
        {title: '리얼 치킨 콥 샐러드',brand: 'side', item_no: 33, src: process.env.PUBLIC_URL + '/assets/side/chi_cob_1.png', sub_src: process.env.PUBLIC_URL + '/assets/side/1664951496.png', cir_img: process.env.PUBLIC_URL + '/assets/side/chi_cob_3.png',title_img:process.env.PUBLIC_URL + '/assets/side/chi_cob_2.png', price: 8500, desc: 'Real Chicken Cobb Salad', opt_color:'#e0f2c4'}, 
        {title: '리얼 아보카도 콥 샐러드', brand: 'side', item_no: 34, src: process.env.PUBLIC_URL + '/assets/side/avo_cob_1.png', sub_src: process.env.PUBLIC_URL + '/assets/side/1646442569(0).png', cir_img: process.env.PUBLIC_URL + '/assets/side/avo_cob_3.png',title_img:process.env.PUBLIC_URL + '/assets/side/avo_cob_2.png', price: 9200, desc: 'Real Avocado Cobb Salad', opt_color:'#e6edda'},
        {title: '딸기잼',brand: 'side', item_no: 35, src: process.env.PUBLIC_URL + '/assets/side/st_1.png', sub_src: process.env.PUBLIC_URL + '/assets/side/st_1.png', cir_img: process.env.PUBLIC_URL + '/assets/side/st_3.png',title_img:process.env.PUBLIC_URL + '/assets/side/st_2.png', price: 300, desc: 'Strawberry Jam', opt_color:'#f593b3'}, 
        {title: '쓰리라찹',brand: 'side', item_no: 36, src: process.env.PUBLIC_URL + '/assets/side/sr_1.png', sub_src: process.env.PUBLIC_URL + '/assets/side/sr_1.png', cir_img: process.env.PUBLIC_URL + '/assets/side/sr_3.png',title_img:process.env.PUBLIC_URL + '/assets/side/sr_2.png', price: 300, desc: 'Srirachup', opt_color:'#fad3c1'}, 
        {title: '반했드랍 반숙란',brand: 'side', item_no: 37, src: process.env.PUBLIC_URL + '/assets/side/soft_e_1.png', sub_src: process.env.PUBLIC_URL + '/assets/side/1686479563(0).png', cir_img: process.env.PUBLIC_URL + '/assets/side/soft_e_3.png',title_img:process.env.PUBLIC_URL + '/assets/side/soft_e_2.png', price: 2800, desc: 'Soft-boiled Egg', opt_color:'#f3d0c0'}, 
    ];    
    export const COFFE = [
        // COFFE
            {title: '(ICE) 아메리카노', brand: 'coffe', item_no: 38, src: process.env.PUBLIC_URL + '/assets/coffe/ame_1.png', sub_src: process.env.PUBLIC_URL + '/assets/coffe/ame_1.png', cir_img: process.env.PUBLIC_URL + '/assets/coffe/ame_3.png',title_img:process.env.PUBLIC_URL + '/assets/coffe/ame_2.png', price: 2400, desc: 'Americano', opt_color:'#f7f6c7'},
            {title: '(ICE) 카페라떼',brand: 'coffe', item_no: 39, src: process.env.PUBLIC_URL + '/assets/coffe/cafe_1.png', sub_src: process.env.PUBLIC_URL + '/assets/coffe/cafe_1.png', cir_img: process.env.PUBLIC_URL + '/assets/coffe/cafe_3.png',title_img:process.env.PUBLIC_URL + '/assets/coffe/cafe_2.png', price: 2900, desc: 'Café Latte', opt_color:'#ddf2bf'}, 
            {title: '(ICE) 수제라떼',brand: 'coffe', item_no: 40, src: process.env.PUBLIC_URL + '/assets/coffe/1680618317.png', sub_src: process.env.PUBLIC_URL + '/assets/coffe/1680618317.png', cir_img: process.env.PUBLIC_URL + '/assets/coffe/1693619686(0).png',title_img:process.env.PUBLIC_URL + '/assets/coffe/1693619727.png', price: 3900, desc: 'Hand-whisked Latte', opt_color:'#fdced6'}, 
            {title: '(ICE) 다크초콜릿모카',brand: 'coffe', item_no: 41, src: process.env.PUBLIC_URL + '/assets/coffe/h_dark_1.png', sub_src: process.env.PUBLIC_URL + '/assets/coffe/h_dark_1.png', cir_img: process.env.PUBLIC_URL + '/assets/coffe/dark_3.png',title_img:process.env.PUBLIC_URL + '/assets/coffe/h_dark_2.png', price: 3900, desc: 'Dark Chocolate Mocha', opt_color:'#ffd8c5'}, 
            {title: '(ICE) 바닐라라떼', brand: 'coffe', item_no: 42, src: process.env.PUBLIC_URL + '/assets/coffe/ba_1.png', sub_src: process.env.PUBLIC_URL + '/assets/coffe/ba_1.png', cir_img: process.env.PUBLIC_URL + '/assets/coffe/ba_3.png',title_img:process.env.PUBLIC_URL + '/assets/coffe/ba_2.png', price: 3400, desc: 'Vanilla Latte', opt_color:'#f7d1ea'},
            {title: '(ICE) 제주말차라떼',brand: 'coffe', item_no: 43, src: process.env.PUBLIC_URL + '/assets/coffe/mal_1.png', sub_src: process.env.PUBLIC_URL + '/assets/coffe/mal_1.png', cir_img: process.env.PUBLIC_URL + '/assets/coffe/mal_3.png',title_img:process.env.PUBLIC_URL + '/assets/coffe/mal_2.png', price: 3400, desc: 'Jeju Matcha Latte', opt_color:'#c3eed9'}, 
            {title: '(ICE) 밀크초콜릿',brand: 'coffe', item_no: 44, src: process.env.PUBLIC_URL + '/assets/coffe/milk_cho_1.png', sub_src: process.env.PUBLIC_URL + '/assets/coffe/milk_cho_1.png', cir_img: process.env.PUBLIC_URL + '/assets/coffe/milk_cho_3.png',title_img:process.env.PUBLIC_URL + '/assets/coffe/milk_cho_2.png', price: 3400, desc: 'Milk Chocolate', opt_color:'#f593b3'}, 
            {title: '(HOT) 아메리카노',brand: 'coffe', item_no: 45, src: process.env.PUBLIC_URL + '/assets/coffe/h_ame_1.png', sub_src: process.env.PUBLIC_URL + '/assets/coffe/h_ame_1.png', cir_img: process.env.PUBLIC_URL + '/assets/coffe/h_ame_3.png',title_img:process.env.PUBLIC_URL + '/assets/coffe/h_ame_2.png', price: 2400, desc: 'Americano', opt_color:'#f7f6c7'}, 
            {title: '(HOT) 카페라떼',brand: 'coffe', item_no: 46, src: process.env.PUBLIC_URL + '/assets/coffe/h_ba_1.png', sub_src: process.env.PUBLIC_URL + '/assets/coffe/h_ba_1.png', cir_img: process.env.PUBLIC_URL + '/assets/coffe/cafe_3.png',title_img:process.env.PUBLIC_URL + '/assets/coffe/cafe_2.png', price: 2900, desc: 'Café Latte', opt_color:'#ddf2bf'}, 
            {title: '(HOT) 수제라떼',brand: 'coffe', item_no: 47, src: process.env.PUBLIC_URL + '/assets/coffe/hand_la_1.png', sub_src: process.env.PUBLIC_URL + '/assets/coffe/hand_la_1.png', cir_img: process.env.PUBLIC_URL + '/assets/coffe/1693619686(0).png',title_img:process.env.PUBLIC_URL + '/assets/coffe/1693619727.png', price: 3900, desc: 'Hand-whisked Latte', opt_color:'#fdced6'},
            {title: '(HOT) 다크초콜릿모카',brand: 'coffe', item_no: 48, src: process.env.PUBLIC_URL + '/assets/coffe/dark_1.png', sub_src: process.env.PUBLIC_URL + '/assets/coffe/dark_1.png', cir_img: process.env.PUBLIC_URL + '/assets/coffe/dark_3.png',title_img:process.env.PUBLIC_URL + '/assets/coffe/h_dark_2.png', price: 3900, desc: 'Dark Chocolate Mocha', opt_color:'#ffd8c5'}, 
            {title: '(HOT) 바닐라라떼', brand: 'coffe', item_no: 49, src: process.env.PUBLIC_URL + '/assets/coffe/h_ba_1.png', sub_src: process.env.PUBLIC_URL + '/assets/coffe/h_ba_1.png', cir_img: process.env.PUBLIC_URL + '/assets/coffe/ba_3.png',title_img:process.env.PUBLIC_URL + '/assets/coffe/ba_2.png', price: 3400, desc: 'Vanilla Latte', opt_color:'#f7d1ea'},
            {title: '(HOT) 제주말차라떼',brand: 'coffe', item_no: 50, src: process.env.PUBLIC_URL + '/assets/coffe/h_mal_1.png', sub_src: process.env.PUBLIC_URL + '/assets/coffe/h_mal_1.png', cir_img: process.env.PUBLIC_URL + '/assets/coffe/mal_3.png',title_img:process.env.PUBLIC_URL + '/assets/coffe/mal_2.png', price: 3400, desc: 'Jeju Matcha Latte', opt_color:'#c3eed9'}, 
            {title: '(HOT) 밀크초콜릿',brand: 'coffe', item_no: 51, src: process.env.PUBLIC_URL + '/assets/coffe/h_ba_1.png', sub_src: process.env.PUBLIC_URL + '/assets/coffe/h_ba_1.png', cir_img: process.env.PUBLIC_URL + '/assets/coffe/milk_cho_3.png',title_img:process.env.PUBLIC_URL + '/assets/coffe/milk_cho_2.png', price: 3400, desc: 'Milk Chocolate', opt_color:'#f593b3'}, 
    ];    
export const DRINK = [
    // DRINK
        {title: '레몬 에이드', brand: 'drink', item_no: 52, src: process.env.PUBLIC_URL + '/assets/drink/101.png', sub_src: process.env.PUBLIC_URL + '/assets/drink/101.png', cir_img: process.env.PUBLIC_URL + '/assets/drink/101_2.png',title_img:process.env.PUBLIC_URL + '/assets/drink/101_1.png', price: 3600, desc: 'Lemon Ade', opt_color:'#f7f6c7'},
        {title: '자몽 에이드',brand: 'drink', item_no: 53, src: process.env.PUBLIC_URL + '/assets/drink/102.png', sub_src: process.env.PUBLIC_URL + '/assets/drink/102.png', cir_img: process.env.PUBLIC_URL + '/assets/drink/102_2.png',title_img:process.env.PUBLIC_URL + '/assets/drink/102_1.png', price: 3600, desc: 'Grapefruit Ade', opt_color:'#fdced6'}, 
        {title: '오렌지 에이드',brand: 'drink', item_no: 54, src: process.env.PUBLIC_URL + '/assets/drink/103.png', sub_src: process.env.PUBLIC_URL + '/assets/drink/103.png', cir_img: process.env.PUBLIC_URL + '/assets/drink/103_2.png',title_img:process.env.PUBLIC_URL + '/assets/drink/103_1.png', price: 3600, desc: 'Orange Ade', opt_color:'#ffd8c5'}, 
        {title: '(ICE) 신선한 우유',brand: 'drink', item_no: 55, src: process.env.PUBLIC_URL + '/assets/drink/105.png', sub_src: process.env.PUBLIC_URL + '/assets/drink/105.png', cir_img: process.env.PUBLIC_URL + '/assets/drink/105_2.png',title_img:process.env.PUBLIC_URL + '/assets/drink/105_1.png', price: 2400, desc: 'Milk', opt_color:'#c8e9f1'}, 
        {title: '(HOT) 신선한 우유', brand: 'drink', item_no: 56, src: process.env.PUBLIC_URL + '/assets/drink/104.png', sub_src: process.env.PUBLIC_URL + '/assets/drink/104.png', cir_img: process.env.PUBLIC_URL + '/assets/drink/104_2.png',title_img:process.env.PUBLIC_URL + '/assets/drink/104_1.png', price: 2400, desc: 'Milk', opt_color:'#c8e9f1'},
];    



export const MAIN_BANNER = [
    // MAIN_BANNER
        {brand: 'banner', item_no: 1, src: process.env.PUBLIC_URL + '/assets/main_banner/main_banner_1.jpg', desc: '메인 배너'},
        {brand: 'banner', item_no: 2, src: process.env.PUBLIC_URL + '/assets/main_banner/main_banner_2.jpg', desc: '메인 배너'}, 
        {brand: 'banner', item_no: 3, src: process.env.PUBLIC_URL + '/assets/main_banner/main_banner_3.jpg', desc: '메인 배너'}, 
        {brand: 'banner', item_no: 4, src: process.env.PUBLIC_URL + '/assets/main_banner/main_banner_4.jpg', desc: '메인 배너'}, 
        {brand: 'banner', item_no: 5, src: process.env.PUBLIC_URL + '/assets/main_banner/main_banner_5.jpg', desc: '메인 배너'},
];   
export const NEW_EGGDROP = [
    // MAIN_BANNER
    {title: '클럽샌드위치', brand: 'banner', item_no: 26, src: process.env.PUBLIC_URL + '/assets/EGGDROP/img_new_1.png', cir_img: process.env.PUBLIC_URL + '/assets/EGGDROP/img_main_new_1.png',title_img: '/assets/EGGDROP/p_new_1.png', desc: '양상추, 베이컨, 토마토와 에그드랍의 특제 소스가 어우러진 베이직한 클럽 샌드위치',opt_color:'#f0ffaa'},
];   

export const ITEMS = [
// SET_ITEMS
    [{title: '미스터 에그 세트', brand: 'set_items', item_no: 1, src: process.env.PUBLIC_URL + '/assets/set_items/Egg_set_1.png', sub_src: process.env.PUBLIC_URL + '/assets/set_items/Egg_set_1.png', cir_img: process.env.PUBLIC_URL + '/assets/set_items/Egg_set_3.png',title_img:process.env.PUBLIC_URL + '/assets/set_items/Egg_set_2.png', price: 7400, desc: 'Mr. Egg Set', opt_color:'#f593b3'},
    {title: '아메리칸 햄 치즈 세트',brand: 'set_items', item_no: 2, src: process.env.PUBLIC_URL + '/assets/set_items/ham_set_1.png', sub_src: process.env.PUBLIC_URL + '/assets/set_items/ham_set_1.png', cir_img: process.env.PUBLIC_URL + '/assets/set_items/ham_set_3.png',title_img:process.env.PUBLIC_URL + '/assets/set_items/ham_set_2.png', price: 8400, desc: 'American Ham Cheese Set', opt_color:'#ffd8c5'}, 
    {title: '베이컨 더블 치즈 세트',brand: 'set_items', item_no: 3, src: process.env.PUBLIC_URL + '/assets/set_items/bacon_1.png', sub_src: process.env.PUBLIC_URL + '/assets/set_items/bacon_1.png', cir_img: process.env.PUBLIC_URL + '/assets/set_items/bacon_3.png',title_img:process.env.PUBLIC_URL + '/assets/set_items/bacon_2.png', price: 8500, desc: 'Bacon Double Cheese Set', opt_color:'#f7f6c7'}, 
    {title: '햄 앤 치즈 프렌치 토스트 세트',brand: 'set_items', item_no: 4, src: process.env.PUBLIC_URL + '/assets/set_items/franch_1.png', sub_src: process.env.PUBLIC_URL + '/assets/set_items/franch_1.png', cir_img: process.env.PUBLIC_URL + '/assets/set_items/franch_3.png',title_img:process.env.PUBLIC_URL + '/assets/set_items/franch_2.png', price: 8400, desc: 'Ham and Cheese French Toast Set', opt_color:'#ddf2bf'}, 
    {title: '갈릭 베이컨 치즈 세트',brand: 'set_items', item_no: 5, src: process.env.PUBLIC_URL + '/assets/set_items/gar_1.png', sub_src: process.env.PUBLIC_URL + '/assets/set_items/gar_1.png', cir_img: process.env.PUBLIC_URL + '/assets/set_items/gar_3.png',title_img:process.env.PUBLIC_URL + '/assets/set_items/gar_2.png', price: 8900, desc: 'Garlic Bacon Cheese Set', opt_color:'#c8e9f1'}, 
    {title: '데리야끼 바베큐 세트', brand: 'set_items', item_no: 6, src: process.env.PUBLIC_URL + '/assets/set_items/teri_1.png', sub_src: process.env.PUBLIC_URL + '/assets/set_items/teri_1.png', cir_img: process.env.PUBLIC_URL + '/assets/set_items/teri_3.png',title_img:process.env.PUBLIC_URL + '/assets/set_items/teri_2.png', price: 9400, desc: 'Teriyaki BBQ Set', opt_color:'#fdced6'},
    {title: '아보홀릭 세트',brand: 'set_items', item_no: 7, src: process.env.PUBLIC_URL + '/assets/set_items/avo_1.png', sub_src: process.env.PUBLIC_URL + '/assets/set_items/avo_1.png', cir_img: process.env.PUBLIC_URL + '/assets/set_items/avo_3.png',title_img:process.env.PUBLIC_URL + '/assets/set_items/avo_2.png', price: 8900, desc: 'Avo Holic Set', opt_color:'#c3eed9'}, 
    {title: '베이컨 딥 치즈 번 세트',brand: 'set_items', item_no: 8, src: process.env.PUBLIC_URL + '/assets/set_items/deep_1.png', sub_src: process.env.PUBLIC_URL + '/assets/set_items/deep_1.png', cir_img: process.env.PUBLIC_URL + '/assets/set_items/deep_3.png',title_img:process.env.PUBLIC_URL + '/assets/set_items/deep_2.png', price: 9100, desc: 'Bacon Deep Cheese Bun Set', opt_color:'#f7d1ea'}, 
    {title: '클럽샌드위치 세트',brand: 'set_items', item_no: 9, src: process.env.PUBLIC_URL + '/assets/set_items/club_1.png', sub_src: process.env.PUBLIC_URL + '/assets/set_items/club_1.png', cir_img: process.env.PUBLIC_URL + '/assets/set_items/club_3.png',title_img:process.env.PUBLIC_URL + '/assets/set_items/club_2.png', price: 8900, desc: 'Club Sandwich Set', opt_color:'#a3efe9'}, 
    {title: '치킨클럽샌드위치 세트',brand: 'set_items', item_no: 10, src: process.env.PUBLIC_URL + '/assets/set_items/chic_1.png', sub_src: process.env.PUBLIC_URL + '/assets/set_items/chic_1.png', cir_img: process.env.PUBLIC_URL + '/assets/set_items/chic_3.png',title_img:process.env.PUBLIC_URL + '/assets/set_items/chic_2.png', price: 9400, desc: 'Chicken Club Sandwich Set', opt_color:'#f4e6e7'},
    {title: '햄 앤 치즈 길거리 토스트 세트',brand: 'set_items', item_no: 11, src: process.env.PUBLIC_URL + '/assets/set_items/street_1.png', sub_src: process.env.PUBLIC_URL + '/assets/set_items/street_1.png', cir_img: process.env.PUBLIC_URL + '/assets/set_items/street_3.png',title_img:process.env.PUBLIC_URL + '/assets/set_items/street_2.png', price: 8400, desc: 'Ham and Cheese K-Street Toast Set', opt_color:'#f2d5b5'}, 
    {title: '치즈 불고기 길거리 토스트 세트', brand: 'set_items', item_no: 12, src: process.env.PUBLIC_URL + '/assets/set_items/bul_1.png', sub_src: process.env.PUBLIC_URL + '/assets/set_items/bul_1.png', cir_img: process.env.PUBLIC_URL + '/assets/set_items/bul_3.png',title_img:process.env.PUBLIC_URL + '/assets/set_items/bul_2.png', price: 9400, desc: 'Cheese Bulgogi K-Street Toast Set', opt_color:'#fce8bd'},
    {title: '아보 베이컨 길거리 토스트 세트',brand: 'set_items', item_no: 13, src: process.env.PUBLIC_URL + '/assets/set_items/avo_str_1.png', sub_src: process.env.PUBLIC_URL + '/assets/set_items/avo_str_1.png', cir_img: process.env.PUBLIC_URL + '/assets/set_items/avo_str_3.png',title_img:process.env.PUBLIC_URL + '/assets/set_items/avo_str_2.png', price: 9400, desc: 'Avo Bacon K-Street Toast Set', opt_color:'#b4e2cc'}, 
    {title: '샐러드 1인 세트',brand: 'set_items', item_no: 14, src: process.env.PUBLIC_URL + '/assets/set_items/sal_1.png', sub_src: process.env.PUBLIC_URL + '/assets/set_items/sal_1.png', cir_img: process.env.PUBLIC_URL + '/assets/set_items/sal_3.png',title_img:process.env.PUBLIC_URL + '/assets/set_items/sal_2.png', price: 10900, desc: 'SALAD SET', opt_color:'#e1e8d5'}, 
    {title: '샌드위치 & 해쉬 & 반했드랍 2인 세트',brand: 'set_items', item_no: 15, src: process.env.PUBLIC_URL + '/assets/set_items/two_san_1.png', sub_src: process.env.PUBLIC_URL + '/assets/set_items/two_san_1.png', cir_img: process.env.PUBLIC_URL + '/assets/set_items/two_san_3.png',title_img:process.env.PUBLIC_URL + '/assets/set_items/two_san_2.png', price: 19900, desc: 'Sandwich & Hash & Half Boiled egg Set for 2 people', opt_color:'#e1e8d5'}, 
    {title: '샌드위치 & 해쉬 & 반했드랍 & 샐러드 3인 세트',brand: 'set_items', item_no: 16, src: process.env.PUBLIC_URL + '/assets/set_items/three_san_1.png', sub_src: process.env.PUBLIC_URL + '/assets/set_items/three_san_1.png', cir_img: process.env.PUBLIC_URL + '/assets/set_items/three_san_3.png',title_img:process.env.PUBLIC_URL + '/assets/set_items/three_san_2.png', price: 35100, desc: 'Sandwich & Hash & Half Boiled egg & Salad', opt_color:'#e1e8d5'}, ],
// SANDWICH
        [{title: '아메리칸 햄 치즈', brand: 'sandwich', item_no: 17, src: process.env.PUBLIC_URL + '/assets/SANDWICH/ame_ham_1.png', sub_src: process.env.PUBLIC_URL + '/assets/SANDWICH/ame_ham_1_1.png', cir_img: process.env.PUBLIC_URL + '/assets/SANDWICH/ame_ham_3.png',title_img:process.env.PUBLIC_URL + '/assets/SANDWICH/ame_ham_2.png', price: 4600, desc: 'American Ham Cheese', opt_color:'#ffd8c5'},
        {title: '햄 앤 치즈 길거리 토스트',brand: 'sandwich', item_no: 18, src: process.env.PUBLIC_URL + '/assets/SANDWICH/ham_1.png', sub_src: process.env.PUBLIC_URL + '/assets/SANDWICH/ham_1_1.png', cir_img: process.env.PUBLIC_URL + '/assets/SANDWICH/ham_3.png',title_img:process.env.PUBLIC_URL + '/assets/SANDWICH/ham_2.png', price: 4900, desc: 'Ham & Cheese K-Street Toast', opt_color:'#f2d5b5'}, 
        {title: '미스터 에그',brand: 'sandwich', item_no: 19, src: process.env.PUBLIC_URL + '/assets/SANDWICH/mr_1.png', sub_src: process.env.PUBLIC_URL + '/assets/SANDWICH/mr_1_1.png', cir_img: process.env.PUBLIC_URL + '/assets/SANDWICH/mr_3.png',title_img:process.env.PUBLIC_URL + '/assets/SANDWICH/mr_2.png', price: 3900, desc: 'Mr. Egg', opt_color:'#f593b3'}, 
        {title: '베이컨 더블 치즈',brand: 'sandwich', item_no: 20, src: process.env.PUBLIC_URL + '/assets/SANDWICH/ba_dou_1.png', sub_src: process.env.PUBLIC_URL + '/assets/SANDWICH/ba_dou_1_1.png', cir_img: process.env.PUBLIC_URL + '/assets/SANDWICH/ba_dou_3.png',title_img:process.env.PUBLIC_URL + '/assets/SANDWICH/ba_dou_2.png', price: 4200, desc: 'Bacon Double Cheese', opt_color:'#f7f6c7'}, 
        {title: '데리야끼 바베큐', brand: 'sandwich', item_no: 21, src: process.env.PUBLIC_URL + '/assets/SANDWICH/tery_1.png', sub_src: process.env.PUBLIC_URL + '/assets/SANDWICH/tery_1_1.png', cir_img: process.env.PUBLIC_URL + '/assets/SANDWICH/tery_3.png',title_img:process.env.PUBLIC_URL + '/assets/SANDWICH/tery_2.png', price: 5400, desc: 'Teriyaki BBQ', opt_color:'#fdced6'},
        {title: '갈릭 베이컨 치즈', brand: 'sandwich', item_no: 22, src: process.env.PUBLIC_URL + '/assets/SANDWICH/gal_1.png', sub_src: process.env.PUBLIC_URL + '/assets/SANDWICH/gal_1_1.png', cir_img: process.env.PUBLIC_URL + '/assets/SANDWICH/gal_3.png',title_img:process.env.PUBLIC_URL + '/assets/SANDWICH/gal_2.png', price: 5200, desc: 'Garlic Bacon Cheese', opt_color:'#c8e9f1'},
        {title: '햄 앤 치즈 프렌치토스트', brand: 'sandwich', item_no: 23, src: process.env.PUBLIC_URL + '/assets/SANDWICH/ham_fr_1.png', sub_src: process.env.PUBLIC_URL + '/assets/SANDWICH/ham_fr_1_1.png', cir_img: process.env.PUBLIC_URL + '/assets/SANDWICH/ham_fr_3.png',title_img:process.env.PUBLIC_URL + '/assets/SANDWICH/ham_fr_2.png', price: 4900, desc: 'Ham & Cheese French Toast', opt_color:'#ddf2bf'},
        {title: '아보홀릭', brand: 'sandwich', item_no: 24, src: process.env.PUBLIC_URL + '/assets/SANDWICH/avo_h_1.png', sub_src: process.env.PUBLIC_URL + '/assets/SANDWICH/avo_h_1_1.png', cir_img: process.env.PUBLIC_URL + '/assets/SANDWICH/avo_h_3.png',title_img:process.env.PUBLIC_URL + '/assets/SANDWICH/avo_h_2.png', price: 5400, desc: 'Avo Holic', opt_color:'#c3eed9'},
        {title: '베이컨 딥 치즈 번', brand: 'sandwich', item_no: 25, src: process.env.PUBLIC_URL + '/assets/SANDWICH/be_deep_1.png', sub_src: process.env.PUBLIC_URL + '/assets/SANDWICH/be_deep_1_1.png', cir_img: process.env.PUBLIC_URL + '/assets/SANDWICH/be_deep_3.png',title_img:process.env.PUBLIC_URL + '/assets/SANDWICH/be_deep_2.png', price: 5400, desc: 'Bacon Deep Cheese Bun', opt_color:'#f7d1ea'},
        {title: '치킨 클럽샌드위치', brand: 'sandwich', item_no: 26, src: process.env.PUBLIC_URL + '/assets/SANDWICH/ch_club_1.png', sub_src: process.env.PUBLIC_URL + '/assets/SANDWICH/ch_club_1_1.png', cir_img: process.env.PUBLIC_URL + '/assets/SANDWICH/ch_club_3.png',title_img:process.env.PUBLIC_URL + '/assets/SANDWICH/ch_club_2.png', price: 6900, desc: 'Chicken Club Sandwich', opt_color:'#f4e6e7'},
        {title: '치즈 불고기 길거리 토스트', brand: 'sandwich', item_no: 27, src: process.env.PUBLIC_URL + '/assets/SANDWICH/ch_bul_1.png', sub_src: process.env.PUBLIC_URL + '/assets/SANDWICH/ch_bul_1_1.png', cir_img: process.env.PUBLIC_URL + '/assets/SANDWICH/ch_bul_3.png',title_img:process.env.PUBLIC_URL + '/assets/SANDWICH/ch_bul_2.png', price: 5900, desc: 'Cheese Bulgogi K-Sreet Toast', opt_color:'#fce8bd'},
        {title: '아보 베이컨 길거리 토스트', brand: 'sandwich', item_no: 28, src: process.env.PUBLIC_URL + '/assets/SANDWICH/avo_str_1.png', sub_src: process.env.PUBLIC_URL + '/assets/SANDWICH/avo_str_1_1.png', cir_img: process.env.PUBLIC_URL + '/assets/SANDWICH/avo_str_3.png',title_img:process.env.PUBLIC_URL + '/assets/SANDWICH/avo_str_2.png', price: 5900, desc: 'Avo Bacon K-Street Toast', opt_color:'#b4e2cc'},],
// SIDE
        [{title: '해쉬브라운', brand: 'side', item_no: 29, src: process.env.PUBLIC_URL + '/assets/side/1702000810(0).png', sub_src: process.env.PUBLIC_URL + '/assets/side/1702000810(0).png', cir_img: process.env.PUBLIC_URL + '/assets/side/hash_3.png',title_img:process.env.PUBLIC_URL + '/assets/side/hash_2.png', price: 1800, desc: 'Hash Brown', opt_color:'#ffcdb4'},
        {title: '베이컨 체다 해쉬브라운',brand: 'side', item_no: 30, src: process.env.PUBLIC_URL + '/assets/side/1702000970(0)(1).png', sub_src: process.env.PUBLIC_URL + '/assets/side/1702000970(0)(1).png', cir_img: process.env.PUBLIC_URL + '/assets/side/b_hash_3.png',title_img:process.env.PUBLIC_URL + '/assets/side/b_hash_2.png', price: 2400, desc: 'Bacon Cheddar HashBrown', opt_color:'#f6d0d9'}, 
        {title: '콘치즈 해쉬브라운',brand: 'side', item_no: 31, src: process.env.PUBLIC_URL + '/assets/side/c_hash_1.png', sub_src: process.env.PUBLIC_URL + '/assets/side/c_hash_1.png', cir_img: process.env.PUBLIC_URL + '/assets/side/c_hash_3.png',title_img:process.env.PUBLIC_URL + '/assets/side/c_hash_2.png', price: 2400, desc: 'Corn Cheese Hash Brown', opt_color:'#fbe7b4'}, 
        {title: '리얼 에그 콥 샐러드',brand: 'side', item_no: 32, src: process.env.PUBLIC_URL + '/assets/side/egg_cob_1.png', sub_src: process.env.PUBLIC_URL + '/assets/side/1646442177(0).png', cir_img: process.env.PUBLIC_URL + '/assets/side/egg_cob_3.png',title_img:process.env.PUBLIC_URL + '/assets/side/egg_cob_2.png', price: 8200, desc: 'Real Egg Cobb Salad', opt_color:'#f0ffaa'}, 
        {title: '리얼 치킨 콥 샐러드',brand: 'side', item_no: 33, src: process.env.PUBLIC_URL + '/assets/side/chi_cob_1.png', sub_src: process.env.PUBLIC_URL + '/assets/side/1664951496.png', cir_img: process.env.PUBLIC_URL + '/assets/side/chi_cob_3.png',title_img:process.env.PUBLIC_URL + '/assets/side/chi_cob_2.png', price: 8500, desc: 'Real Chicken Cobb Salad', opt_color:'#e0f2c4'}, 
        {title: '리얼 아보카도 콥 샐러드', brand: 'side', item_no: 34, src: process.env.PUBLIC_URL + '/assets/side/avo_cob_1.png', sub_src: process.env.PUBLIC_URL + '/assets/side/1646442569(0).png', cir_img: process.env.PUBLIC_URL + '/assets/side/avo_cob_3.png',title_img:process.env.PUBLIC_URL + '/assets/side/avo_cob_2.png', price: 9200, desc: 'Real Avocado Cobb Salad', opt_color:'#e6edda'},
        {title: '딸기잼',brand: 'side', item_no: 35, src: process.env.PUBLIC_URL + '/assets/side/st_1.png', sub_src: process.env.PUBLIC_URL + '/assets/side/st_1.png', cir_img: process.env.PUBLIC_URL + '/assets/side/st_3.png',title_img:process.env.PUBLIC_URL + '/assets/side/st_2.png', price: 300, desc: 'Strawberry Jam', opt_color:'#f593b3'}, 
        {title: '쓰리라찹',brand: 'side', item_no: 36, src: process.env.PUBLIC_URL + '/assets/side/sr_1.png', sub_src: process.env.PUBLIC_URL + '/assets/side/sr_1.png', cir_img: process.env.PUBLIC_URL + '/assets/side/sr_3.png',title_img:process.env.PUBLIC_URL + '/assets/side/sr_2.png', price: 300, desc: 'Srirachup', opt_color:'#fad3c1'}, 
        {title: '반했드랍 반숙란',brand: 'side', item_no: 37, src: process.env.PUBLIC_URL + '/assets/side/soft_e_1.png', sub_src: process.env.PUBLIC_URL + '/assets/side/1686479563(0).png', cir_img: process.env.PUBLIC_URL + '/assets/side/soft_e_3.png',title_img:process.env.PUBLIC_URL + '/assets/side/soft_e_2.png', price: 2800, desc: 'Soft-boiled Egg', opt_color:'#f3d0c0'}, ],
// COFFE
        [{title: '(ICE) 아메리카노', brand: 'coffe', item_no: 38, src: process.env.PUBLIC_URL + '/assets/coffe/ame_1.png', sub_src: process.env.PUBLIC_URL + '/assets/coffe/ame_1.png', cir_img: process.env.PUBLIC_URL + '/assets/coffe/ame_3.png',title_img:process.env.PUBLIC_URL + '/assets/coffe/ame_2.png', price: 2400, desc: 'Americano', opt_color:'#f7f6c7'},
        {title: '(ICE) 카페라떼',brand: 'coffe', item_no: 39, src: process.env.PUBLIC_URL + '/assets/coffe/cafe_1.png', sub_src: process.env.PUBLIC_URL + '/assets/coffe/cafe_1.png', cir_img: process.env.PUBLIC_URL + '/assets/coffe/cafe_3.png',title_img:process.env.PUBLIC_URL + '/assets/coffe/cafe_2.png', price: 2900, desc: 'Café Latte', opt_color:'#ddf2bf'}, 
        {title: '(ICE) 수제라떼',brand: 'coffe', item_no: 40, src: process.env.PUBLIC_URL + '/assets/coffe/1680618317.png', sub_src: process.env.PUBLIC_URL + '/assets/coffe/1680618317.png', cir_img: process.env.PUBLIC_URL + '/assets/coffe/1693619686(0).png',title_img:process.env.PUBLIC_URL + '/assets/coffe/1693619727.png', price: 3900, desc: 'Hand-whisked Latte', opt_color:'#fdced6'}, 
        {title: '(ICE) 다크초콜릿모카',brand: 'coffe', item_no: 41, src: process.env.PUBLIC_URL + '/assets/coffe/h_dark_1.png', sub_src: process.env.PUBLIC_URL + '/assets/coffe/h_dark_1.png', cir_img: process.env.PUBLIC_URL + '/assets/coffe/dark_3.png',title_img:process.env.PUBLIC_URL + '/assets/coffe/h_dark_2.png', price: 3900, desc: 'Dark Chocolate Mocha', opt_color:'#ffd8c5'}, 
        {title: '(ICE) 바닐라라떼', brand: 'coffe', item_no: 42, src: process.env.PUBLIC_URL + '/assets/coffe/ba_1.png', sub_src: process.env.PUBLIC_URL + '/assets/coffe/ba_1.png', cir_img: process.env.PUBLIC_URL + '/assets/coffe/ba_3.png',title_img:process.env.PUBLIC_URL + '/assets/coffe/ba_2.png', price: 3400, desc: 'Vanilla Latte', opt_color:'#f7d1ea'},
        {title: '(ICE) 제주말차라떼',brand: 'coffe', item_no: 43, src: process.env.PUBLIC_URL + '/assets/coffe/mal_1.png', sub_src: process.env.PUBLIC_URL + '/assets/coffe/mal_1.png', cir_img: process.env.PUBLIC_URL + '/assets/coffe/mal_3.png',title_img:process.env.PUBLIC_URL + '/assets/coffe/mal_2.png', price: 3400, desc: 'Jeju Matcha Latte', opt_color:'#c3eed9'}, 
        {title: '(ICE) 밀크초콜릿',brand: 'coffe', item_no: 44, src: process.env.PUBLIC_URL + '/assets/coffe/milk_cho_1.png', sub_src: process.env.PUBLIC_URL + '/assets/coffe/milk_cho_1.png', cir_img: process.env.PUBLIC_URL + '/assets/coffe/milk_cho_3.png',title_img:process.env.PUBLIC_URL + '/assets/coffe/milk_cho_2.png', price: 3400, desc: 'Milk Chocolate', opt_color:'#f593b3'}, 
        {title: '(HOT) 아메리카노',brand: 'coffe', item_no: 45, src: process.env.PUBLIC_URL + '/assets/coffe/h_ame_1.png', sub_src: process.env.PUBLIC_URL + '/assets/coffe/h_ame_1.png', cir_img: process.env.PUBLIC_URL + '/assets/coffe/h_ame_3.png',title_img:process.env.PUBLIC_URL + '/assets/coffe/h_ame_2.png', price: 2400, desc: 'Americano', opt_color:'#f7f6c7'}, 
        {title: '(HOT) 카페라떼',brand: 'coffe', item_no: 46, src: process.env.PUBLIC_URL + '/assets/coffe/h_ba_1.png', sub_src: process.env.PUBLIC_URL + '/assets/coffe/h_ba_1.png', cir_img: process.env.PUBLIC_URL + '/assets/coffe/cafe_3.png',title_img:process.env.PUBLIC_URL + '/assets/coffe/cafe_2.png', price: 2900, desc: 'Café Latte', opt_color:'#ddf2bf'}, 
        {title: '(HOT) 수제라떼',brand: 'coffe', item_no: 47, src: process.env.PUBLIC_URL + '/assets/coffe/hand_la_1.png', sub_src: process.env.PUBLIC_URL + '/assets/coffe/hand_la_1.png', cir_img: process.env.PUBLIC_URL + '/assets/coffe/1693619686(0).png',title_img:process.env.PUBLIC_URL + '/assets/coffe/1693619727.png', price: 3900, desc: 'Hand-whisked Latte', opt_color:'#fdced6'},
        {title: '(HOT) 다크초콜릿모카',brand: 'coffe', item_no: 48, src: process.env.PUBLIC_URL + '/assets/coffe/dark_1.png', sub_src: process.env.PUBLIC_URL + '/assets/coffe/dark_1.png', cir_img: process.env.PUBLIC_URL + '/assets/coffe/dark_3.png',title_img:process.env.PUBLIC_URL + '/assets/coffe/h_dark_2.png', price: 3900, desc: 'Dark Chocolate Mocha', opt_color:'#ffd8c5'}, 
        {title: '(HOT) 바닐라라떼', brand: 'coffe', item_no: 49, src: process.env.PUBLIC_URL + '/assets/coffe/h_ba_1.png', sub_src: process.env.PUBLIC_URL + '/assets/coffe/h_ba_1.png', cir_img: process.env.PUBLIC_URL + '/assets/coffe/ba_3.png',title_img:process.env.PUBLIC_URL + '/assets/coffe/ba_2.png', price: 3400, desc: 'Vanilla Latte', opt_color:'#f7d1ea'},
        {title: '(HOT) 제주말차라떼',brand: 'coffe', item_no: 50, src: process.env.PUBLIC_URL + '/assets/coffe/h_mal_1.png', sub_src: process.env.PUBLIC_URL + '/assets/coffe/h_mal_1.png', cir_img: process.env.PUBLIC_URL + '/assets/coffe/mal_3.png',title_img:process.env.PUBLIC_URL + '/assets/coffe/mal_2.png', price: 3400, desc: 'Jeju Matcha Latte', opt_color:'#c3eed9'}, 
        {title: '(HOT) 밀크초콜릿',brand: 'coffe', item_no: 51, src: process.env.PUBLIC_URL + '/assets/coffe/h_ba_1.png', sub_src: process.env.PUBLIC_URL + '/assets/coffe/h_ba_1.png', cir_img: process.env.PUBLIC_URL + '/assets/coffe/milk_cho_3.png',title_img:process.env.PUBLIC_URL + '/assets/coffe/milk_cho_2.png', price: 3400, desc: 'Milk Chocolate', opt_color:'#f593b3'}, ],
// DRINK
        [{title: '레몬 에이드', brand: 'drink', item_no: 52, src: process.env.PUBLIC_URL + '/assets/drink/101.png', sub_src: process.env.PUBLIC_URL + '/assets/drink/101.png', cir_img: process.env.PUBLIC_URL + '/assets/drink/101_2.png',title_img:process.env.PUBLIC_URL + '/assets/drink/101_1.png', price: 3600, desc: 'Lemon Ade', opt_color:'#f7f6c7'},
        {title: '자몽 에이드',brand: 'drink', item_no: 53, src: process.env.PUBLIC_URL + '/assets/drink/102.png', sub_src: process.env.PUBLIC_URL + '/assets/drink/102.png', cir_img: process.env.PUBLIC_URL + '/assets/drink/102_2.png',title_img:process.env.PUBLIC_URL + '/assets/drink/102_1.png', price: 3600, desc: 'Grapefruit Ade', opt_color:'#fdced6'}, 
        {title: '오렌지 에이드',brand: 'drink', item_no: 54, src: process.env.PUBLIC_URL + '/assets/drink/103.png', sub_src: process.env.PUBLIC_URL + '/assets/drink/103.png', cir_img: process.env.PUBLIC_URL + '/assets/drink/103_2.png',title_img:process.env.PUBLIC_URL + '/assets/drink/103_1.png', price: 3600, desc: 'Orange Ade', opt_color:'#ffd8c5'}, 
        {title: '(ICE) 신선한 우유',brand: 'drink', item_no: 55, src: process.env.PUBLIC_URL + '/assets/drink/105.png', sub_src: process.env.PUBLIC_URL + '/assets/drink/105.png', cir_img: process.env.PUBLIC_URL + '/assets/drink/105_2.png',title_img:process.env.PUBLIC_URL + '/assets/drink/105_1.png', price: 2400, desc: 'Milk', opt_color:'#c8e9f1'}, 
        {title: '(HOT) 신선한 우유', brand: 'drink', item_no: 56, src: process.env.PUBLIC_URL + '/assets/drink/104.png', sub_src: process.env.PUBLIC_URL + '/assets/drink/104.png', cir_img: process.env.PUBLIC_URL + '/assets/drink/104_2.png',title_img:process.env.PUBLIC_URL + '/assets/drink/104_1.png', price: 2400, desc: 'Milk', opt_color:'#c8e9f1'},]

];    
export const MENU_HEADER = ["EGGDROP’s CHOICE",'SANDWICH', 'SIDE', 'COFFEE', 'DRINK',]
